@echo off
REM Remove files generated by compiler in this directory
REM and all subdirectories.

echo Removing *.$$$ files...
del *.$$$ /f /q
echo.

echo Removing *.bkx files...
del *.bkx /f /q
echo.

echo Removing *.cce files...
del *.cce /f /q
echo.

echo Removing *.cod files...
del *.cod /f /q
echo.

echo Removing *.cof files...
del *.cof /f /q
echo.

echo Removing *.err files...
del *.err /f /q
echo.

rem echo Removing *.hex files...
rem del *.hex /f /q
rem echo.

echo Removing *.i files...
del *.i /f /q
echo.

echo Removing *.lde files...
del *.lde /f /q
echo.

echo Removing *.lst files...
del *.lst /f /q
echo.

echo Removing *.obj files...
del *.obj /f /q
echo.

echo Removing *.o files...
del *.o /f /q
echo.

echo Removing *.rlf files...
del *.rlf /f /q
echo.

echo Removing *.sym files...
del *.sym /f /q
echo.

echo Removing *.sdb files...
del *.sdb /f /q
echo.

echo Removing *.wat files...
del *.wat /f /q
echo.

echo Removing *.mcs files...
del *.mcs /f /q
echo.

echo Removing *.mptags files...
del *.mptags /f /q
echo.

echo Removing *.tagsrc files...
del *.tagsrc /f /q
echo.

echo Removing *.map files...
del *.map /f /q
echo.

echo Removing *.elf files...
del *.elf /f /q
echo.

echo Removing *.p1 files...
del *.p1 /f /q
echo.

echo Removing *.dep files...
del *.dep /f /q
echo.

echo Removing startup.as file...
del startup.as /f /q
echo.

rd Objects /Q

echo Done.